### ISSUE TITLE
Recieving Server Errors on Windows Version

### ISSUE THREAD

**Issue by yuu1412** [kanashter/bothermione-ao3wrapped#3]
hi! sorry if this isn't the place for this but i didn't want to clog your twitter notifications >3<

running the desktop version on my windows (Win 10 Prow x64 bit) i get the following:
"Looks like there was a server error! If you're positive you got your password right, please try again later!"

but the weird thing is, i can run different accounts with no errors (both before and after receiving this) so i was wondering if there's anything i can do that would stop such an error from happening? i checked to make sure the password is correct to the username it just... doeesn't seem to like that particular account.

**Comment by kanashter** [comment]
Hello!

If this is for a single account, it must be due to having a very, very large history with it! AO3 is annoying in that it will only ever display 20 items per page - so when it has to request to see a lot of pages AO3 will just say no, and the whole thing breaks.

I'm working on a local version with timeouts built into it so it can return (wont be feasible online due to length of time required), but it may take a little time sorry!

As a quick sidenote so I can diagnose a bit better, do you get the error immediately, or after a few seconds?

**Comment by kanashter** [comment]
Could you give this version a go?

Might take 10+ minutes to load!

https://github.com/kanashter/bothermione-ao3wrapped/releases/tag/v1.0.2

**Comment by yuu1412** [comment]
nope that uh, timed out and gave me the same error about 5 seconds after running ;A;

**Comment by yuu1412** [comment]
oh whoops, missed the sidenote in the first message - it normally takes about 4 to 5 seconds on the online / original ao3wrapped desktop version!  
also thank you for trying ;A; i guess i just... read a lot more than i expected despite the time where i was only reading danmei

**Comment by kanashter** [comment]
Oh no! It's possible there's an issue with the original flask server not closing correctly on your computer, could you go into task manager (ctrl shift esc) and see if theres a process called ao3 running? Will look like the following: 

![Screenshot 2021-12-15 090730](https://user-images.githubusercontent.com/49260416/146071750-772d4f6e-44ae-4bd6-bc95-bc53b5f1c2a1.jpg)

If there is, please kill it and try again! Sorry for the difficulties.

**Comment by yuu1412** [comment]
Tried that and it took a bit longer (aprox 6s) before I got the error instead ;A;
(no, don't apologize! thank you so much for making this app and trying to help)

**Comment by kanashter** [comment]
Hrm! How odd. A 6s timeout implies something is breaking rather than the process actually running. Will have to do some thinking there sorry!
