### ISSUE TITLE
Ships/Tags incorrect?

### ISSUE THREAD

**Issue by actuallyrandomperson** [kanashter/bothermione-ao3wrapped#5]
I just did this today, and while the word count seems to be accurate based on previous years of stats, it seems to have counted both this year & last year in regards to the top ships (and maybe tags, though I'm less sure on that). I noticed because my top ship was for a fandom I read fic for religiously last year, and subsequently avoided like the plague this year, and even though I did read a handful of fics for it, it definitely wasn't enough to get it on the list at all, let alone the top position. Also, the intro text still says '2021'

**Comment by moon-dew** [comment]
The year that the code is checking needs to be updated, so I'd guess everything you're looking at is for last year, once it's been updated, it should be accurate, alternatively download the files, go into flaskserver/functions.py, and find line 50 which currently says
`if temp_fic['dt'] >= datetime(2021, 1, 1, 0, 0):`
and just change 2021 to 2022

**Comment by kanashter** [comment]
Resolved in latest version
